# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.3"
manifest_format = "2.0"
project_hash = "dcaf7630aac6aeaf9fe03557f31bdb7767d0d72a"

[[deps.CftAnyons]]
path = "."
uuid = "30962e7d-9b68-4193-a327-46f53f748341"
version = "0.1.0"
