# JonesWenzlKernel.jl
#
# CA-74: identify the one-dimensional kernel of rho_4 for Fibonacci dilute TL.
# The numerical object is the dense-corner Jones-Wenzl element evaluated through
# the CA-73 generator matrices.  The formal word expansion is carried alongside
# the matrices so the coefficient of the corner-unit diagram is checked before
# quotienting by the Fibonacci representation.
#
# Source: references/text/TemperleyLiebRootsJonesQuotient.txt:136-140
#   Jones-Wenzl idempotent characterized by generator annihilation at roots of
#   unity; the radical ideal is generated by this idempotent.
# Source: literature/md/1710.07362/1710.07362.md:30-33
#   local extraction records the recursive Jones-Wenzl definition, but loses the
#   diagram factor in the second term; the tests below therefore pin the defining
#   idempotent and annihilation properties rather than trusting the extraction.
# Source: report/sections/69_dilute_tl_word_algebra.tex:38-48, 126-128
#   dense corners pi_A dTL_n pi_A are TL_|A|; the first expected kernel is the
#   dense TL_4 negligible Jones-Wenzl projector at beta = phi.

const _JWWord = Tuple{Vararg{Int}}

struct JonesWenzlProjector
    L::Int
    k::Int
    beta::Float64
    quantum_integers::Vector{Float64}
    blocks::Dict{Symbol,Matrix{Float64}}
    expansion::Dict{_JWWord,Float64}
end

_identity_block(L::Integer, charge::Symbol) = begin
    n = length(fibonacci_word_sector_basis(L, charge))
    Matrix{Float64}(I, n, n)
end

"""
    corner_unit(L) -> Dict{Symbol,Matrix{Float64}}

The fully occupied dense-corner unit `Pi_A`, built as the product of single-site
occupancy projectors on each charge sector of `O^tensor L`.
"""
function corner_unit(L::Integer)
    L >= 1 || error("corner_unit needs L >= 1, got $L")
    out = Dict{Symbol,Matrix{Float64}}()
    for charge in _FIB_CHARGES
        P = _identity_block(L, charge)
        for site in 1:L
            Nsite =
                L == 1 ? Matrix{Float64}(occupation_number_matrix(L, site, charge)) :
                site < L ? local_two_site_matrix(occupancy_blocks(:left), site, L, charge) :
                local_two_site_matrix(occupancy_blocks(:right), L - 1, L, charge)
            P = P * Nsite
        end
        out[charge] = P
    end
    return out
end

"""
    dense_corner_tl_generators(L) -> Vector{Dict{Symbol,Matrix{Float64}}}

Corner-compressed dense Temperley-Lieb generators `E_j = Pi_A e_j Pi_A`,
`j = 1,...,L-1`, evaluated on the CA-66 path basis.
"""
function dense_corner_tl_generators(L::Integer)
    L >= 2 || error("dense_corner_tl_generators needs L >= 2, got $L")
    Pi = corner_unit(L)
    return [Dict(charge => Pi[charge] *
                           local_two_site_matrix(dense_e_blocks(), j, L, charge) *
                           Pi[charge]
                 for charge in _FIB_CHARGES)
            for j in 1:(L - 1)]
end

"""
    jw_quantum_integers(n; beta = golden_ratio()) -> Vector{Float64}

Quantum integers `[1],...,[n]` from `[1]=1`, `[2]=beta`,
`[m+1]=beta[m]-[m-1]`.
"""
function jw_quantum_integers(n::Integer; beta::Real = golden_ratio())
    n >= 1 || error("need at least [1], got n=$n")
    qs = zeros(Float64, n)
    qs[1] = 1.0
    n >= 2 && (qs[2] = Float64(beta))
    for m in 2:(n - 1)
        qs[m + 1] = Float64(beta) * qs[m] - qs[m - 1]
    end
    return qs
end

function _word_scaled_add!(out::Dict{_JWWord,Float64}, word::_JWWord, coeff::Real)
    out[word] = get(out, word, 0.0) + Float64(coeff)
    abs(out[word]) < 1e-14 && delete!(out, word)
    return out
end

function _wenzl_expansion_step(expansion::Dict{_JWWord,Float64}, j::Integer,
                               coeff::Real)
    out = copy(expansion)
    for (left_word, left_coeff) in expansion, (right_word, right_coeff) in expansion
        word = (left_word..., Int(j), right_word...)
        _word_scaled_add!(out, word, -Float64(coeff) * left_coeff * right_coeff)
    end
    return out
end

"""
    jones_wenzl_projector(L, k; beta = golden_ratio()) -> JonesWenzlProjector

Evaluate the dense-corner Wenzl recursion for `p_k` inside the length-`L`
corner, using `p_1 = Pi_A` and
`p_{r+1} = p_r - ([r]/[r+1]) p_r E_r p_r`.
"""
function jones_wenzl_projector(L::Integer, k::Integer; beta::Real = golden_ratio())
    L >= 1 || error("L must be positive, got $L")
    1 <= k <= L || error("need 1 <= k <= L, got k=$k, L=$L")
    k == 1 && return JonesWenzlProjector(
        Int(L), Int(k), Float64(beta), jw_quantum_integers(2; beta),
        corner_unit(L), Dict{_JWWord,Float64}(() => 1.0))

    qints = jw_quantum_integers(k + 1; beta)
    Es = dense_corner_tl_generators(L)
    blocks = Dict(charge => copy(corner_unit(L)[charge]) for charge in _FIB_CHARGES)
    expansion = Dict{_JWWord,Float64}(() => 1.0)

    for r in 1:(k - 1)
        denom = qints[r + 1]
        abs(denom) > 1e-13 || error("Wenzl recursion denominator [$r+1] is zero")
        coeff = qints[r] / denom
        blocks = Dict(charge => blocks[charge] -
                                coeff * blocks[charge] * Es[r][charge] * blocks[charge]
                      for charge in _FIB_CHARGES)
        expansion = _wenzl_expansion_step(expansion, r, coeff)
    end

    return JonesWenzlProjector(Int(L), Int(k), Float64(beta), qints, blocks, expansion)
end

jones_wenzl_projector_blocks(L::Integer, k::Integer; beta::Real = golden_ratio()) =
    jones_wenzl_projector(L, k; beta).blocks

unit_word_coefficient(p::JonesWenzlProjector) = get(p.expansion, (), 0.0)

function nonunit_words_contain_generator(p::JonesWenzlProjector)
    return all(!isempty(word) for word in keys(p.expansion) if word != ())
end

block_opnorm(blocks::Dict{Symbol,<:AbstractMatrix}) =
    maximum(opnorm(blocks[charge]) for charge in _FIB_CHARGES)

block_frobenius_norm(blocks::Dict{Symbol,<:AbstractMatrix}) =
    sqrt(sum(norm(blocks[charge])^2 for charge in _FIB_CHARGES))

"""
    parity_refined_multiplicities(L) -> Dict

Pure path-count split of each charge multiplicity by occupied-number parity.
"""
function parity_refined_multiplicities(L::Integer)
    L >= 0 || error("L must be nonnegative, got $L")
    out = Dict{Symbol,NamedTuple{(:even, :odd),Tuple{Int,Int}}}()
    for charge in _FIB_CHARGES
        basis = fibonacci_word_sector_basis(L, charge)
        even = count(entry -> iseven(length(entry[1])), basis)
        out[charge] = (even = even, odd = length(basis) - even)
    end
    return out
end

function parity_even_dimension_from_counts(L::Integer)
    counts = parity_refined_multiplicities(L)
    return sum(counts[charge].even^2 + counts[charge].odd^2 for charge in _FIB_CHARGES)
end
